name: TensorFlow Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.3'

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libgl1-mesa-glx
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        output=$(python main.py -i C.png --load)
        echo "$output"

        if echo "$output" | grep -q "Predicted label: C"; then
          echo "Prediction test passed"
        else
          echo "Prediction test failed"
          exit 1
        fi